import { env } from "cloudflare:workers";
import { desc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { documents } from "../../../db/schema";
const bucket=()=>((env as unknown as {FILES:R2Bucket}).FILES);
export async function GET(request:Request){try{const url=new URL(request.url);const id=Number(url.searchParams.get("download"));if(id){const[row]=await getDb().select().from(documents).where(eq(documents.id,id)).limit(1);if(!row)return new Response("Dokument nije pronađen.",{status:404});const object=await bucket().get(row.storageKey);if(!object)return new Response("Fajl nije pronađen.",{status:404});return new Response(object.body,{headers:{"Content-Type":row.mimeType,"Content-Disposition":`attachment; filename*=UTF-8''${encodeURIComponent(row.name)}`}})}return Response.json({documents:await getDb().select().from(documents).orderBy(desc(documents.id))})}catch(e){return Response.json({error:e instanceof Error?e.message:"Dokumenti nisu učitani."},{status:500})}}
export async function POST(request:Request){try{const form=await request.formData();const file=form.get("file");if(!(file instanceof File)||!file.size)return Response.json({error:"Izaberite fajl za otpremanje."},{status:400});if(file.size>10*1024*1024)return Response.json({error:"Maksimalna veličina fajla je 10 MB."},{status:400});const folder=String(form.get("folder")||"Ostalo");const key=`documents/${Date.now()}-${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;await bucket().put(key,file.stream(),{httpMetadata:{contentType:file.type||"application/octet-stream"}});const[document]=await getDb().insert(documents).values({name:file.name,folder,linkedTo:String(form.get("linkedTo")||""),uploadedBy:"Marko Nikolić",mimeType:file.type||"application/octet-stream",size:file.size,storageKey:key,expiresAt:String(form.get("expiresAt")||"")||null}).returning();return Response.json({document},{status:201})}catch(e){return Response.json({error:e instanceof Error?e.message:"Dokument nije otpremljen."},{status:500})}}
export async function PATCH(request:Request){try{const b=await request.json() as {id:number;name:string;folder:string;linkedTo:string;expiresAt?:string};const[document]=await getDb().update(documents).set({name:b.name.trim(),folder:b.folder,linkedTo:b.linkedTo.trim(),expiresAt:b.expiresAt||null}).where(eq(documents.id,Number(b.id))).returning();if(!document)return Response.json({error:"Dokument nije pronađen."},{status:404});return Response.json({document})}catch(e){return Response.json({error:e instanceof Error?e.message:"Izmene nisu sačuvane."},{status:500})}}
export async function DELETE(request:Request){try{const id=Number(new URL(request.url).searchParams.get("id"));const[row]=await getDb().select().from(documents).where(eq(documents.id,id)).limit(1);if(!row)return Response.json({error:"Dokument nije pronađen."},{status:404});await bucket().delete(row.storageKey);await getDb().delete(documents).where(eq(documents.id,id));return Response.json({deleted:true})}catch(e){return Response.json({error:e instanceof Error?e.message:"Dokument nije obrisan."},{status:500})}}
